# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            ej
tagline:          software writer in pdx
url:              http://www.ejohnson.io
paginate:         1
baseurl:          /
author:
  name:           Eric Johnson
  url:            https://twitter.com/realrearwheel
  email:          erjohnson.pdx@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
